import type { Experience } from "./types";

/**
 * Typed seed set (IMP-002 §9) matching the 20 experiences already visible
 * in `/labs/discovery-space`. This validates the schema, the filtering
 * rules, and Discovery integration — it is not production data.
 *
 * Metadata confidence: moods/activities/seasons/timeOfDay/weather/
 * companions/energyLevel/priceLevel/duration are best-effort editorial
 * guesses based on each experience's name and tagline, not verified facts,
 * partner-provided data, or a real taxonomy review. `accessible` is
 * omitted everywhere on purpose — no real accessibility information
 * exists yet, and guessing it would be actively misleading rather than
 * just imprecise. `location` gives a name/region only; real latitude and
 * longitude are omitted rather than invented. Only Campfire has real
 * `heroMedia` (the Living Passport Card); every other experience omits
 * `heroMedia` rather than referencing a photo/video asset that doesn't
 * exist on disk.
 */
export const SEED_EXPERIENCES: Experience[] = [
  {
    id: "campfire",
    slug: "campfire",
    title: "Campfire",
    shortDescription: "Embers under an open sky.",
    tier: 1,
    heroMedia: {
      type: "video",
      src: "/video/campfire-summer.mp4",
      alt: "A campfire burning at dusk beside a lake.",
    },
    moods: ["relaxing", "romantic", "cozy"],
    activities: ["campfire", "storytelling"],
    seasons: ["summer", "fall"],
    timeOfDay: ["evening", "night"],
    weather: ["clear", "calm"],
    companions: ["partner", "friends", "family"],
    energyLevel: 1,
    priceLevel: 0,
    duration: { minMinutes: 60, maxMinutes: 180 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    location: { name: "Okanagan Lake shoreline", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "wake-boat",
    slug: "wake-boat",
    title: "Wake Boat",
    shortDescription: "Cut a line across still water.",
    tier: 2,
    moods: ["thrilling", "energetic"],
    activities: ["water sports", "boating"],
    seasons: ["summer"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["clear", "warm"],
    companions: ["friends", "group"],
    energyLevel: 4,
    priceLevel: 3,
    duration: { minMinutes: 60, maxMinutes: 120 },
    familyFriendly: true,
    petFriendly: false,
    requiresReservation: true,
    location: { name: "Okanagan Lake", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "helicopter-tour",
    slug: "helicopter-tour",
    title: "Helicopter Tour",
    shortDescription: "Everything, smaller and clearer.",
    tier: 2,
    moods: ["thrilling", "awe"],
    activities: ["sightseeing", "adventure"],
    seasons: ["spring", "summer", "fall"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["clear"],
    companions: ["partner", "friends", "solo"],
    energyLevel: 2,
    priceLevel: 4,
    duration: { minMinutes: 30, maxMinutes: 60 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    location: { name: "Kelowna", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "hidden-beach",
    slug: "hidden-beach",
    title: "Hidden Beach",
    shortDescription: "Only reachable if you look.",
    tier: 2,
    moods: ["relaxing", "adventurous"],
    activities: ["swimming", "exploring"],
    seasons: ["summer"],
    timeOfDay: ["afternoon"],
    weather: ["warm", "clear"],
    companions: ["partner", "solo", "friends"],
    energyLevel: 3,
    priceLevel: 0,
    duration: { minMinutes: 60, maxMinutes: 240 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    location: { name: "Okanagan Lake", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "bbq-feast",
    slug: "bbq-feast",
    title: "BBQ Feast",
    shortDescription: "Smoke, slow and unhurried.",
    tier: 3,
    moods: ["relaxing", "social"],
    activities: ["dining", "gathering"],
    seasons: ["summer"],
    timeOfDay: ["afternoon", "evening"],
    weather: ["clear", "warm"],
    companions: ["family", "friends", "group"],
    energyLevel: 1,
    priceLevel: 2,
    duration: { minMinutes: 90, maxMinutes: 150 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "stargazing",
    slug: "stargazing",
    title: "Stargazing",
    shortDescription: "Further from everything, closer to this.",
    tier: 2,
    moods: ["relaxing", "romantic", "awe"],
    activities: ["stargazing"],
    seasons: ["summer", "fall"],
    timeOfDay: ["night"],
    weather: ["clear"],
    companions: ["partner", "solo", "family"],
    energyLevel: 1,
    priceLevel: 0,
    duration: { minMinutes: 60, maxMinutes: 180 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "spa-escape",
    slug: "spa-escape",
    title: "Spa Escape",
    shortDescription: "Slower breathing, on purpose.",
    tier: 3,
    moods: ["relaxing", "restorative"],
    activities: ["spa", "wellness"],
    seasons: ["spring", "summer", "fall", "winter"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["clear", "cold", "warm"],
    companions: ["solo", "partner"],
    energyLevel: 1,
    priceLevel: 3,
    duration: { minMinutes: 60, maxMinutes: 180 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    isActive: true,
  },
  {
    id: "winery",
    slug: "winery",
    title: "Winery",
    shortDescription: "Rows that took decades to get right.",
    tier: 3,
    moods: ["relaxing", "romantic", "social"],
    activities: ["wine tasting", "touring"],
    seasons: ["summer", "fall"],
    timeOfDay: ["afternoon"],
    weather: ["clear"],
    companions: ["partner", "friends", "group"],
    energyLevel: 1,
    priceLevel: 2,
    duration: { minMinutes: 60, maxMinutes: 120 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    location: { name: "Naramata Bench", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "coffee",
    slug: "coffee",
    title: "Coffee",
    shortDescription: "The good kind, made slowly.",
    tier: 2,
    moods: ["relaxing", "cozy"],
    activities: ["coffee", "cafe"],
    seasons: ["spring", "summer", "fall", "winter"],
    timeOfDay: ["morning"],
    weather: ["clear", "cold", "warm", "rain", "snow"],
    companions: ["solo", "partner", "friends"],
    energyLevel: 1,
    priceLevel: 1,
    duration: { minMinutes: 20, maxMinutes: 60 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "paddle-board",
    slug: "paddle-board",
    title: "Paddle Board",
    shortDescription: "Balance, then quiet.",
    tier: 2,
    moods: ["relaxing", "active"],
    activities: ["water sports", "paddleboarding"],
    seasons: ["summer"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["calm", "clear"],
    companions: ["solo", "partner", "friends"],
    energyLevel: 3,
    priceLevel: 1,
    duration: { minMinutes: 45, maxMinutes: 90 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "snowmobile",
    slug: "snowmobile",
    title: "Snowmobile",
    shortDescription: "Fresh lines, nobody else's.",
    tier: 3,
    moods: ["thrilling", "adventurous"],
    activities: ["snowmobiling"],
    seasons: ["winter"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["snow", "cold"],
    companions: ["friends", "partner", "group"],
    energyLevel: 4,
    priceLevel: 3,
    duration: { minMinutes: 60, maxMinutes: 120 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    isActive: true,
  },
  {
    id: "chef-dinner",
    slug: "chef-dinner",
    title: "Chef Dinner",
    shortDescription: "A table set for exactly you.",
    tier: 3,
    moods: ["romantic", "indulgent"],
    activities: ["dining"],
    seasons: ["spring", "summer", "fall", "winter"],
    timeOfDay: ["evening"],
    weather: ["clear", "cold", "warm", "rain", "snow"],
    companions: ["partner", "family", "friends"],
    energyLevel: 1,
    priceLevel: 4,
    duration: { minMinutes: 90, maxMinutes: 180 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    isActive: true,
  },
  {
    id: "cabin",
    slug: "cabin",
    title: "Cabin",
    shortDescription: "A door that locks out everything else.",
    tier: 2,
    moods: ["relaxing", "cozy", "restorative"],
    activities: ["lodging", "retreat"],
    seasons: ["fall", "winter"],
    timeOfDay: ["evening", "night"],
    weather: ["cold", "snow"],
    companions: ["partner", "family", "solo"],
    energyLevel: 1,
    priceLevel: 3,
    duration: { minMinutes: 720, maxMinutes: 2880 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: true,
    isActive: true,
  },
  {
    id: "mountain-bike",
    slug: "mountain-bike",
    title: "Mountain Bike",
    shortDescription: "Trails that argue back.",
    tier: 3,
    moods: ["thrilling", "active"],
    activities: ["mountain biking"],
    seasons: ["spring", "summer", "fall"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["clear"],
    companions: ["friends", "solo", "group"],
    energyLevel: 5,
    priceLevel: 1,
    duration: { minMinutes: 60, maxMinutes: 180 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "fire-lookout",
    slug: "fire-lookout",
    title: "Fire Lookout",
    shortDescription: "One room, above the treeline.",
    tier: 2,
    moods: ["adventurous", "awe", "relaxing"],
    activities: ["hiking", "lodging"],
    seasons: ["summer", "fall"],
    timeOfDay: ["afternoon", "evening"],
    weather: ["clear"],
    companions: ["partner", "solo", "friends"],
    energyLevel: 3,
    priceLevel: 2,
    duration: { minMinutes: 720, maxMinutes: 2880 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: true,
    isActive: true,
  },
  {
    id: "ice-fishing",
    slug: "ice-fishing",
    title: "Ice Fishing",
    shortDescription: "Patience, rewarded occasionally.",
    tier: 3,
    moods: ["relaxing"],
    activities: ["fishing"],
    seasons: ["winter"],
    timeOfDay: ["morning", "afternoon"],
    weather: ["cold", "snow"],
    companions: ["solo", "friends", "family"],
    energyLevel: 1,
    priceLevel: 1,
    duration: { minMinutes: 120, maxMinutes: 240 },
    familyFriendly: true,
    petFriendly: false,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "lake-cruise",
    slug: "lake-cruise",
    title: "Lake Cruise",
    shortDescription: "The shoreline, from the water.",
    tier: 2,
    moods: ["relaxing", "romantic"],
    activities: ["boating", "sightseeing"],
    seasons: ["summer"],
    timeOfDay: ["afternoon", "evening"],
    weather: ["clear", "calm"],
    companions: ["partner", "family", "friends"],
    energyLevel: 1,
    priceLevel: 2,
    duration: { minMinutes: 60, maxMinutes: 120 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: true,
    location: { name: "Okanagan Lake", region: "Okanagan Valley" },
    isActive: true,
  },
  {
    id: "hot-springs",
    slug: "hot-springs",
    title: "Hot Springs",
    shortDescription: "Warm water, cold air.",
    tier: 3,
    moods: ["relaxing", "restorative"],
    activities: ["hot springs", "wellness"],
    seasons: ["fall", "winter"],
    timeOfDay: ["afternoon", "evening"],
    weather: ["cold", "snow"],
    companions: ["partner", "solo", "friends"],
    energyLevel: 1,
    priceLevel: 2,
    duration: { minMinutes: 60, maxMinutes: 120 },
    familyFriendly: true,
    petFriendly: false,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "live-music",
    slug: "live-music",
    title: "Live Music",
    shortDescription: "Close enough to feel the bass.",
    tier: 3,
    moods: ["energetic", "social"],
    activities: ["live music", "nightlife"],
    seasons: ["summer"],
    timeOfDay: ["evening", "night"],
    weather: ["clear", "warm", "cold"],
    companions: ["friends", "partner", "group"],
    energyLevel: 3,
    priceLevel: 2,
    duration: { minMinutes: 120, maxMinutes: 240 },
    familyFriendly: false,
    petFriendly: false,
    requiresReservation: false,
    isActive: true,
  },
  {
    id: "sunset-dock",
    slug: "sunset-dock",
    title: "Sunset Dock",
    shortDescription: "The best seat, and it's free.",
    tier: 3,
    moods: ["relaxing", "romantic"],
    activities: ["sightseeing"],
    seasons: ["summer", "fall"],
    timeOfDay: ["evening"],
    weather: ["clear"],
    companions: ["partner", "solo", "family", "friends"],
    energyLevel: 1,
    priceLevel: 0,
    duration: { minMinutes: 30, maxMinutes: 90 },
    familyFriendly: true,
    petFriendly: true,
    requiresReservation: false,
    location: { name: "Okanagan Lake shoreline", region: "Okanagan Valley" },
    isActive: true,
  },
];
