import type { FieldExperience } from "./types";

/**
 * Placeholder discoveries for the Discovery Space prototype.
 * Positions are hand-scattered (not generated) so the field reads as
 * organic rather than gridded, and stays clear of the pinned Mood Board
 * on the right ~30% of the viewport. Glow tones are deliberately muted —
 * a single soft light source per card, not a saturated gradient badge —
 * to keep the field feeling closer to a museum installation than a poster.
 */
export const EXPERIENCES: FieldExperience[] = [
  {
    id: "campfire",
    name: "Campfire",
    tagline: "Embers under an open sky.",
    glow: "from-amber-200/14 to-transparent",
    life: "ember",
    temptation: "ember",
    video: "/video/campfire-summer.mp4",
    layout: {
      top: 8,
      left: 12,
      size: 190,
      rotate: -3,
      depth: 0.85,
      duration: 23,
      delay: 0,
      driftX: 10,
      driftY: 8,
    },
  },
  {
    id: "wake-boat",
    name: "Wake Boat",
    tagline: "Cut a line across still water.",
    glow: "from-slate-300/14 to-transparent",
    life: "shimmer",
    layout: {
      top: 22,
      left: 42,
      size: 210,
      rotate: 2,
      depth: 0.5,
      duration: 28,
      delay: 1.2,
      driftX: 14,
      driftY: 10,
    },
  },
  {
    id: "helicopter-tour",
    name: "Helicopter Tour",
    tagline: "Everything, smaller and clearer.",
    glow: "from-slate-300/14 to-transparent",
    life: "still",
    temptation: "glint",
    layout: {
      top: 4,
      left: 54,
      size: 170,
      rotate: -2,
      depth: 0.35,
      duration: 32,
      delay: 2.4,
      driftX: 8,
      driftY: 14,
    },
  },
  {
    id: "hidden-beach",
    name: "Hidden Beach",
    tagline: "Only reachable if you look.",
    glow: "from-teal-200/14 to-transparent",
    life: "whisper",
    temptation: "ripple",
    layout: {
      top: 34,
      left: 6,
      size: 230,
      rotate: 3,
      depth: 0.95,
      duration: 21,
      delay: 0.6,
      driftX: 12,
      driftY: 9,
    },
  },
  {
    id: "bbq-feast",
    name: "BBQ Feast",
    tagline: "Smoke, slow and unhurried.",
    glow: "from-amber-200/14 to-transparent",
    life: "ember",
    layout: {
      top: 15,
      left: 30,
      size: 150,
      rotate: -4,
      depth: 0.4,
      duration: 30,
      delay: 3.1,
      driftX: 9,
      driftY: 12,
    },
  },
  {
    id: "stargazing",
    name: "Stargazing",
    tagline: "Further from everything, closer to this.",
    glow: "from-violet-200/14 to-transparent",
    life: "shimmer",
    temptation: "shooting-star",
    layout: {
      top: 62,
      left: 18,
      size: 220,
      rotate: 2,
      depth: 0.9,
      duration: 25,
      delay: 1.8,
      driftX: 11,
      driftY: 15,
    },
  },
  {
    id: "spa-escape",
    name: "Spa Escape",
    tagline: "Slower breathing, on purpose.",
    glow: "from-yellow-100/14 to-transparent",
    life: "breathing",
    temptation: "steam",
    layout: {
      top: 48,
      left: 48,
      size: 180,
      rotate: -2,
      depth: 0.55,
      duration: 29,
      delay: 0.3,
      driftX: 13,
      driftY: 8,
    },
  },
  {
    id: "winery",
    name: "Winery",
    tagline: "Rows that took decades to get right.",
    glow: "from-violet-200/14 to-transparent",
    life: "still",
    layout: {
      top: 72,
      left: 40,
      size: 200,
      rotate: 3,
      depth: 0.7,
      duration: 24,
      delay: 2.9,
      driftX: 10,
      driftY: 11,
    },
  },
  {
    id: "coffee",
    name: "Coffee",
    tagline: "The good kind, made slowly.",
    glow: "from-amber-100/16 to-transparent",
    life: "still",
    temptation: "steam",
    layout: {
      top: 5,
      left: 24,
      size: 130,
      rotate: -1,
      depth: 0.3,
      duration: 34,
      delay: 4.2,
      driftX: 7,
      driftY: 10,
    },
  },
  {
    id: "paddle-board",
    name: "Paddle Board",
    tagline: "Balance, then quiet.",
    glow: "from-teal-200/14 to-transparent",
    life: "still",
    temptation: "ripple",
    layout: {
      top: 40,
      left: 55,
      size: 160,
      rotate: -3,
      depth: 0.45,
      duration: 31,
      delay: 1.1,
      driftX: 12,
      driftY: 9,
    },
  },
  {
    id: "snowmobile",
    name: "Snowmobile",
    tagline: "Fresh lines, nobody else's.",
    glow: "from-slate-300/14 to-transparent",
    life: "still",
    layout: {
      top: 78,
      left: 8,
      size: 200,
      rotate: 2,
      depth: 0.65,
      duration: 26,
      delay: 3.5,
      driftX: 9,
      driftY: 13,
    },
  },
  {
    id: "chef-dinner",
    name: "Chef Dinner",
    tagline: "A table set for exactly you.",
    glow: "from-amber-200/14 to-transparent",
    life: "whisper",
    layout: {
      top: 58,
      left: 30,
      size: 175,
      rotate: -2,
      depth: 0.6,
      duration: 28,
      delay: 0.9,
      driftX: 8,
      driftY: 10,
    },
  },
  {
    id: "cabin",
    name: "Cabin",
    tagline: "A door that locks out everything else.",
    glow: "from-emerald-200/12 to-transparent",
    life: "still",
    temptation: "window-glow",
    layout: {
      top: 78,
      left: 26,
      size: 210,
      rotate: 1,
      depth: 0.8,
      duration: 22,
      delay: 2.1,
      driftX: 14,
      driftY: 7,
    },
  },
  {
    id: "mountain-bike",
    name: "Mountain Bike",
    tagline: "Trails that argue back.",
    glow: "from-emerald-200/12 to-transparent",
    life: "still",
    layout: {
      top: 28,
      left: 20,
      size: 165,
      rotate: -4,
      depth: 0.5,
      duration: 30,
      delay: 4.8,
      driftX: 10,
      driftY: 12,
    },
  },
  {
    id: "fire-lookout",
    name: "Fire Lookout",
    tagline: "One room, above the treeline.",
    glow: "from-amber-200/14 to-transparent",
    life: "ember",
    layout: {
      top: 12,
      left: 46,
      size: 145,
      rotate: 4,
      depth: 0.3,
      duration: 33,
      delay: 1.6,
      driftX: 6,
      driftY: 14,
    },
  },
  {
    id: "ice-fishing",
    name: "Ice Fishing",
    tagline: "Patience, rewarded occasionally.",
    glow: "from-slate-300/14 to-transparent",
    life: "whisper",
    layout: {
      top: 66,
      left: 52,
      size: 155,
      rotate: -2,
      depth: 0.4,
      duration: 29,
      delay: 3.9,
      driftX: 9,
      driftY: 8,
    },
  },
  {
    id: "lake-cruise",
    name: "Lake Cruise",
    tagline: "The shoreline, from the water.",
    glow: "from-teal-200/14 to-transparent",
    life: "shimmer",
    layout: {
      top: 50,
      left: 6,
      size: 195,
      rotate: 2,
      depth: 0.75,
      duration: 23,
      delay: 0.4,
      driftX: 12,
      driftY: 10,
    },
  },
  {
    id: "hot-springs",
    name: "Hot Springs",
    tagline: "Warm water, cold air.",
    glow: "from-violet-200/14 to-transparent",
    life: "breathing",
    layout: {
      top: 80,
      left: 46,
      size: 185,
      rotate: -3,
      depth: 0.55,
      duration: 31,
      delay: 2.6,
      driftX: 11,
      driftY: 9,
    },
  },
  {
    id: "live-music",
    name: "Live Music",
    tagline: "Close enough to feel the bass.",
    glow: "from-violet-200/14 to-transparent",
    life: "whisper",
    layout: {
      top: 36,
      left: 34,
      size: 140,
      rotate: 4,
      depth: 0.35,
      duration: 32,
      delay: 5.2,
      driftX: 7,
      driftY: 13,
    },
  },
  {
    id: "sunset-dock",
    name: "Sunset Dock",
    tagline: "The best seat, and it's free.",
    glow: "from-yellow-100/14 to-transparent",
    life: "breathing",
    layout: {
      top: 76,
      left: 14,
      size: 205,
      rotate: -1,
      depth: 0.85,
      duration: 25,
      delay: 1.4,
      driftX: 13,
      driftY: 11,
    },
  },
];
